export const componentMaptoName={
    CaptureTemplate:"Capture Report Template",
    RegOpzDataGrid:"Data Grid",
    MaintainBusinessRules:"Maintain Business Rules",
    AddBusinessRule:"Add Business Rule",
    ViewDataComponentV2:"View Data",
    ViewDataComponent:"View Data",
    ViewReport:"View Report",
    CreateReport:"Create Report",
    DrillDown:"DrillDown",
    MaintainReportRules:"Maintain Report Rules",
    AddReportRules:"Add Report Rules",
    AddReportAggRules:"Add Report Aggregate Rules",
    MaintainSources:"Maintain Sources",
    AddSources:"Add Sources",
    VarianceAnalysis:"Variance Analysis",
    ManageDefChange:"Manage Definition Change",
    ManageDataChange:"Manage Data Change",
    ManageRolesComponent:"Manage Roles",
    ManageUsersComponent:"Manage Users",
    LoadData: "Load Data",
    ManageSubscribersComponent: "Subscriber Management",
    MaintainBusinessRulesRepository: "Maintain Business Rules Repository"

}
